Class {
	#name : #HomeAutomationAnnoucement,
	#superclass : #Announcement,
	#category : #'PharoHomeAutomation-Core'
}

{ #category : #testing }
HomeAutomationAnnoucement >> isDeviceAnnoucement [
	^false.
]

{ #category : #accessing }
HomeAutomationAnnoucement >> isDeviceAnnoucement: aBlock [
	
]

{ #category : #testing }
HomeAutomationAnnoucement >> isTimeAnnoucement [
	^false.
]

{ #category : #testing }
HomeAutomationAnnoucement >> isTimeAnnoucement: aBlock [

]
